name: Build Windows stuff

on: push

jobs:
  build:
    runs-on: windows-2019
    env:
      # vcpkg 2020.07 release
      vcpkg_version: '56fffbe49dfb4dd8fae0940f272c5fd2b86be991'
      vcpkg_directory: '${{ github.workspace }}/vcpkg'

      python_version: '3.8'

    steps:
    # Set up the required python version and install dependencies
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.python_version }}
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pyinstaller pylint pycodestyle
    - name: Checkout
      uses: actions/checkout@v2
    - name: CMake
      run: cmake . -DPython3_ROOT_DIR=${env:pythonLocal} -DPython3_FIND_STRATEGY=LOCATION