name: Build Windows stuff

on: push

jobs:
  build:
    runs-on: windows-2019
    env:
      python_version: '3.8'

    steps:
    # Set up the required python version and install dependencies
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.python_version }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: CMake
      run: |
        mkdir build
        cd build
        cmake ..